version: '3.8'

services:
  # API Service
  api:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile
    container_name: growvia-tracking-api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://mongo:27017/growvia
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CORS_ORIGIN=*
      - DEFAULT_ATTRIBUTION_MODEL=last-click
      - DEFAULT_CONVERSION_WINDOW=604800
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    networks:
      - growvia-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MongoDB
  mongo:
    image: mongo:6
    container_name: growvia-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=growvia
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    restart: unless-stopped
    networks:
      - growvia-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/growvia --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Redis
  redis:
    image: redis:6-alpine
    container_name: growvia-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - growvia-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    command: redis-server --appendonly yes

  # MongoDB Express (Optional - for development)
  mongo-express:
    image: mongo-express:latest
    container_name: growvia-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - growvia-network
    profiles:
      - dev

  # Redis Commander (Optional - for development)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: growvia-redis-commander
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - growvia-network
    profiles:
      - dev

networks:
  growvia-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local
  redis-data:
    driver: local
